,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/47983,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47983/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47983/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47983/events,https://github.com/pandas-dev/pandas/issues/47983,1330040995,I_kwDOAA0YD85PRtCj,47983,BUG: Dataframe.to_xml() fails with control characters,"{'login': 'CarlosHartmann', 'id': 65766894, 'node_id': 'MDQ6VXNlcjY1NzY2ODk0', 'avatar_url': 'https://avatars.githubusercontent.com/u/65766894?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/CarlosHartmann', 'html_url': 'https://github.com/CarlosHartmann', 'followers_url': 'https://api.github.com/users/CarlosHartmann/followers', 'following_url': 'https://api.github.com/users/CarlosHartmann/following{/other_user}', 'gists_url': 'https://api.github.com/users/CarlosHartmann/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/CarlosHartmann/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/CarlosHartmann/subscriptions', 'organizations_url': 'https://api.github.com/users/CarlosHartmann/orgs', 'repos_url': 'https://api.github.com/users/CarlosHartmann/repos', 'events_url': 'https://api.github.com/users/CarlosHartmann/events{/privacy}', 'received_events_url': 'https://api.github.com/users/CarlosHartmann/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-05T14:53:13Z,2022-08-05T14:59:08Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

csv_content = b'''FOO,BAR,BYTES\nfoo,bar,""Next byte is a control char \x13""\n'''

with open('file.csv', 'wb') as outfile:
    outfile.write(csv_content)

df = pd.read_csv('file.csv', sep=',')

df.to_xml('file.xml')
```


### Issue Description

The process fails without writing anything into an XML file and without giving any information about the positiong or which char/byte caused the failure.



This is the error message:

```
File ""/opt/miniconda3/envs/pylaia/lib/python3.7/site-packages/pandas/core/frame.py"", line 2986, in to_xml
    return xml_formatter.write_output()
  File ""/opt/miniconda3/envs/pylaia/lib/python3.7/site-packages/pandas/io/formats/xml.py"", line 265, in write_output
    xml_doc = self.build_tree()
  File ""/opt/miniconda3/envs/pylaia/lib/python3.7/site-packages/pandas/io/formats/xml.py"", line 485, in build_tree
    self.build_elems()
  File ""/opt/miniconda3/envs/pylaia/lib/python3.7/site-packages/pandas/io/formats/xml.py"", line 575, in build_elems
    SubElement(self.elem_row, elem_name).text = val
  File ""src/lxml/etree.pyx"", line 1024, in lxml.etree._Element.text.__set__
  File ""src/lxml/apihelpers.pxi"", line 747, in lxml.etree._setNodeText
  File ""src/lxml/apihelpers.pxi"", line 735, in lxml.etree._createTextNode
  File ""src/lxml/apihelpers.pxi"", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

### Expected Behavior

Please forgive if my assumption is wrong or Pandas is not the right place to report this, I'm fairly new to Pandas.

I would expect either of those behaviors:

1. Delete the control characters without feedback to the user. Or maybe have delete_non-utf8 as an option for to_xml.
2. Replace them with an HTML entity, like `&#019;` for the character above that causes the failure.
3. Fail but indicate which character caused the issue and perhaps also its position.

Again I'm fairly new. I thought 1. was going to happen because I am fairly sure that in the data I was handling there was ANSI content in an otherwise UTF-8-encoded file. Somehow, Pandas handled it without issue. That's why I thought Pandas would be robust to any such issues.

If my assumption is wrong and the current behavior is preferred over 1, I would like to suggest Nr. 3 as it would have made work slightly easier with a large amount of data in my dataframe.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.7.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-84-generic
Version          : #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.20.2
pytz             : 2022.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.8.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47983/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47983/timeline,,,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/47982,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47982/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47982/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47982/events,https://github.com/pandas-dev/pandas/issues/47982,1329981412,I_kwDOAA0YD85PRefk,47982,"ENH: support pd.NA in ""category"" dtype","{'login': 'devmcp', 'id': 48351339, 'node_id': 'MDQ6VXNlcjQ4MzUxMzM5', 'avatar_url': 'https://avatars.githubusercontent.com/u/48351339?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/devmcp', 'html_url': 'https://github.com/devmcp', 'followers_url': 'https://api.github.com/users/devmcp/followers', 'following_url': 'https://api.github.com/users/devmcp/following{/other_user}', 'gists_url': 'https://api.github.com/users/devmcp/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/devmcp/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/devmcp/subscriptions', 'organizations_url': 'https://api.github.com/users/devmcp/orgs', 'repos_url': 'https://api.github.com/users/devmcp/repos', 'events_url': 'https://api.github.com/users/devmcp/events{/privacy}', 'received_events_url': 'https://api.github.com/users/devmcp/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-08-05T14:02:11Z,2022-08-05T14:15:05Z,,NONE,,"### Feature Type

- [x] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

I would like to be able to use `pd.NA` for missing data in a column of dtype ""category""

Currently this:

```
pd.DataFrame({""A"": [""one"", ""two"", pd.NA]}).astype(""category"")
```

converts the `pd.NA` to `np.NaN`.

### Feature Description

I think there should be a ""category"" dtype that supports `pd.NA`.

### Alternative Solutions

I don't think there is a current workaround

### Additional Context

_No response_","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47982/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47982/timeline,,,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/47981,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47981/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47981/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47981/events,https://github.com/pandas-dev/pandas/pull/47981,1329973079,PR_kwDOAA0YD848uF8z,47981,TST: GH39984 Addition to tests,"{'login': 'BarkotBeyene', 'id': 38720673, 'node_id': 'MDQ6VXNlcjM4NzIwNjcz', 'avatar_url': 'https://avatars.githubusercontent.com/u/38720673?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/BarkotBeyene', 'html_url': 'https://github.com/BarkotBeyene', 'followers_url': 'https://api.github.com/users/BarkotBeyene/followers', 'following_url': 'https://api.github.com/users/BarkotBeyene/following{/other_user}', 'gists_url': 'https://api.github.com/users/BarkotBeyene/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/BarkotBeyene/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/BarkotBeyene/subscriptions', 'organizations_url': 'https://api.github.com/users/BarkotBeyene/orgs', 'repos_url': 'https://api.github.com/users/BarkotBeyene/repos', 'events_url': 'https://api.github.com/users/BarkotBeyene/events{/privacy}', 'received_events_url': 'https://api.github.com/users/BarkotBeyene/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-08-05T13:55:10Z,2022-08-05T14:12:43Z,,CONTRIBUTOR,,"- [x] closes #GH39984 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47981/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47981/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47981', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47981', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47981.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47981.patch', 'merged_at': None}"
3,https://api.github.com/repos/pandas-dev/pandas/issues/47979,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47979/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47979/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47979/events,https://github.com/pandas-dev/pandas/pull/47979,1329921675,PR_kwDOAA0YD848t6vO,47979,DEPS: Update cython,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-08-05T13:10:09Z,2022-08-05T15:01:58Z,,MEMBER,,- [x] closes #47978,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47979/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47979/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47979', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47979', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47979.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47979.patch', 'merged_at': None}"
4,https://api.github.com/repos/pandas-dev/pandas/issues/47978,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47978/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47978/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47978/events,https://github.com/pandas-dev/pandas/issues/47978,1329837714,I_kwDOAA0YD85PQ7aS,47978,BUILD: Bump Cython again to (at least) 0.29.31,"{'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}","[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNTA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Build', 'name': 'Build', 'color': '75507B', 'default': False, 'description': 'Library building on various platforms'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/96', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96/labels', 'id': 8104401, 'node_id': 'MI_kwDOAA0YD84Ae6nR', 'number': 96, 'title': '1.4.4', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 35, 'closed_issues': 42, 'state': 'open', 'created_at': '2022-06-21T19:44:05Z', 'updated_at': '2022-08-05T11:51:43Z', 'due_on': '2022-08-31T07:00:00Z', 'closed_at': None}",0,2022-08-05T11:51:43Z,2022-08-05T11:51:43Z,,MEMBER,,"in [1.4.3](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.3.html#other) we bumped Cython to 0.29.30 xref [GH41935](https://github.com/pandas-dev/pandas/issues/41935)

Ideally we want to bump Cython again to (at least) 0.29.31 in 1.4.x to fix a recent regression #46848 but also to address a long standing underlying issue of the pandas implementations of `take` that sometimes segfault with object dtypes.

cc @lithomas1","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47978/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47978/timeline,,,,
5,https://api.github.com/repos/pandas-dev/pandas/issues/47975,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47975/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47975/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47975/events,https://github.com/pandas-dev/pandas/pull/47975,1329257803,PR_kwDOAA0YD848rscP,47975,REF: Move Series logic from Index._get_values_for_loc,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-08-04T23:01:27Z,2022-08-04T23:01:27Z,,MEMBER,,Cleaner abstraction.,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47975/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47975/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47975', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47975', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47975.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47975.patch', 'merged_at': None}"
6,https://api.github.com/repos/pandas-dev/pandas/issues/47974,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47974/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47974/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47974/events,https://github.com/pandas-dev/pandas/issues/47974,1329235469,I_kwDOAA0YD85POoYN,47974,DOC: Signature information for groupby.aggregate does not include Named Aggregation,"{'login': 'DRudel', 'id': 5006589, 'node_id': 'MDQ6VXNlcjUwMDY1ODk=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5006589?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/DRudel', 'html_url': 'https://github.com/DRudel', 'followers_url': 'https://api.github.com/users/DRudel/followers', 'following_url': 'https://api.github.com/users/DRudel/following{/other_user}', 'gists_url': 'https://api.github.com/users/DRudel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/DRudel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/DRudel/subscriptions', 'organizations_url': 'https://api.github.com/users/DRudel/orgs', 'repos_url': 'https://api.github.com/users/DRudel/repos', 'events_url': 'https://api.github.com/users/DRudel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/DRudel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-04T22:29:49Z,2022-08-04T22:29:49Z,,NONE,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html?highlight=aggregate#pandas.core.groupby.DataFrameGroupBy.aggregate

### Documentation problem

The entry for Groupby.Aggregate() describes _Named Aggregation_ at the bottom of its entry, but this support is now exposed in the signature information defining the inputs at the top of the page. Also, I would claim that the description for _**kwargs_ is now outdated, for **kwargs now serves a different role when _func_ is _None_.

Notably, someone looking at signature information would think that Aggregate() and Transform() can take the same types of input, but that is not true, since Transform() does not support Named Aggregation.


### Suggested fix for documentation

- Add a note to the _func_ signature description indicating that when _func_ == None, the _Named Aggregation_ is assumed (with a reference to the User Guide page)
- Update the _**kwargs_ signature to indicate that when _func_ == None, the keywords are not passed along to the function but are used to define the Named Aggregation","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47974/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47974/timeline,,,,
7,https://api.github.com/repos/pandas-dev/pandas/issues/47973,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47973/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47973/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47973/events,https://github.com/pandas-dev/pandas/pull/47973,1329188975,PR_kwDOAA0YD848reOS,47973,TST/CLN: Consolidate creation of groupby method args,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean', 'name': 'Clean', 'color': '207de5', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 74, 'closed_issues': 1240, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-08-05T12:56:48Z', 'due_on': '2022-07-31T07:00:00Z', 'closed_at': None}",0,2022-08-04T21:23:17Z,2022-08-05T12:56:48Z,,MEMBER,,"- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Wasn't sure if it was better to put the helper in `__init__`  or create `common`.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47973/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47973/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47973', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47973', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47973.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47973.patch', 'merged_at': None}"
8,https://api.github.com/repos/pandas-dev/pandas/issues/47972,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47972/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47972/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47972/events,https://github.com/pandas-dev/pandas/pull/47972,1329187603,PR_kwDOAA0YD848rd7i,47972,BUG: pivot_table raising TypeError with ea dtype and dropna True,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}, {'id': 1817503692, 'node_id': 'MDU6TGFiZWwxODE3NTAzNjky', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays', 'name': 'NA - MaskedArrays', 'color': '8cc645', 'default': False, 'description': 'Related to pd.NA and nullable extension arrays'}]",open,False,,[],,0,2022-08-04T21:21:29Z,2022-08-04T21:21:42Z,,MEMBER,,"- [x] closes #47477 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

The aggregation function already provides the correct dtype. In case of numpy dtype we are casting to many cases, see #47971","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47972/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47972/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47972', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47972', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47972.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47972.patch', 'merged_at': None}"
9,https://api.github.com/repos/pandas-dev/pandas/issues/47971,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47971/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47971/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47971/events,https://github.com/pandas-dev/pandas/issues/47971,1329180699,I_kwDOAA0YD85PObAb,47971,BUG: pivot_table downcasting dtypes even if not necessary,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-04T21:13:04Z,2022-08-04T21:14:39Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
df = pd.DataFrame({""x"": ""a"", ""y"": ""b"", ""age"": [20, 40]})
result = df.pivot_table(
    index='x', columns='y', values='age', aggfunc='mean', dropna=True
)

result = df.pivot_table(
    index='x', columns='y', values='age', aggfunc='mean', dropna=False
)
```


### Issue Description

with ``dropna=True`` this returns ``int64`` dtype, while we get ``float64`` with ``dropna=False``. This happens because we try to downcast if we set dropna, because we drop all nan rows which cast our dtypes to float.

But the downcast path is also hit, when we don't have all nan rows and hence the aggregation function returned the correct dtype all along. 

### Expected Behavior

I think both cases should be consistent if no nans are dropped, e.g. we should not try to downcast.


If we want to do this, we should probably deprecate or changing in 2.0, but not in a minor release

### Installed Versions

<details>
main

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47971/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47971/timeline,,,,
10,https://api.github.com/repos/pandas-dev/pandas/issues/47970,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47970/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47970/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47970/events,https://github.com/pandas-dev/pandas/pull/47970,1329151254,PR_kwDOAA0YD848rWKR,47970,REF: Use `Styler` implementation for `DataFrame.to_latex`,"{'login': 'attack68', 'id': 24256554, 'node_id': 'MDQ6VXNlcjI0MjU2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/attack68', 'html_url': 'https://github.com/attack68', 'followers_url': 'https://api.github.com/users/attack68/followers', 'following_url': 'https://api.github.com/users/attack68/following{/other_user}', 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions', 'organizations_url': 'https://api.github.com/users/attack68/orgs', 'repos_url': 'https://api.github.com/users/attack68/repos', 'events_url': 'https://api.github.com/users/attack68/events{/privacy}', 'received_events_url': 'https://api.github.com/users/attack68/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-08-04T20:38:08Z,2022-08-04T20:38:08Z,,CONTRIBUTOR,,"After a year of patching up things in #41649, and @jreback merge of #47864 I can finally propose this for review.

# Objective

- Maintain `DataFrame.to_latex` with its existing arguments, adding no arguments
- Process the rendering via `Styler.to_latex`
- Eliminate the need  for `LatexFormatter` (code removal not part of this PR) and dual pandas code systems.
- Redocument and direct users to the `Styler` implementation for forward development

# Outcome

- All arguments in `DataFrame.to_latex` were replicable, with the exception of `col_space` which has no impact upon latex render and, I personally don't like anyway. `col_space` is deprecated with warning and test.
- All original tests pass with minor changes to latex formatting and no significant changes to latex render.
- Some default formatting of floats changes based on pandas Styler options and DataFrame options crossover, which should be addressed later.
- The performance of `Styler` is marginally better, although for the table sizes that one would like to render in latex is neglible, anyway.

No whats_new: awaiting feedback.

# New docs

The key new section of the docs..

![Screenshot 2022-08-04 at 22 19 37](https://user-images.githubusercontent.com/24256554/182947439-22693f13-bc7f-4392-a4d4-f1bfc5f32df5.png)




","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47970/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47970/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47970', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47970', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47970.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47970.patch', 'merged_at': None}"
11,https://api.github.com/repos/pandas-dev/pandas/issues/47964,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47964/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47964/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47964/events,https://github.com/pandas-dev/pandas/issues/47964,1328710718,I_kwDOAA0YD85PMoQ-,47964,STYLE check pandas doesn't use external package when that package is vendored,"{'login': 'MarcoGorelli', 'id': 33491632, 'node_id': 'MDQ6VXNlcjMzNDkxNjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MarcoGorelli', 'html_url': 'https://github.com/MarcoGorelli', 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers', 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}', 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions', 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs', 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos', 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events', 'type': 'User', 'site_admin': False}","[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Code%20Style', 'name': 'Code Style', 'color': 'eb6420', 'default': False, 'description': 'Code style, linting, code_checks'}]",open,False,,[],,0,2022-08-04T14:19:13Z,2022-08-04T14:19:13Z,,MEMBER,,xref https://github.com/pandas-dev/pandas/pull/47939#issue-1326760809,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47964/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47964/timeline,,,,
12,https://api.github.com/repos/pandas-dev/pandas/issues/47963,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47963/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47963/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47963/events,https://github.com/pandas-dev/pandas/issues/47963,1328495790,I_kwDOAA0YD85PLzyu,47963,BUG: `pd.Grouper` creates empty groups (and in doing so is inconsistent with `groupby`) with `pd.DatetimeIndex`,"{'login': 'bollard', 'id': 358225, 'node_id': 'MDQ6VXNlcjM1ODIyNQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/358225?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bollard', 'html_url': 'https://github.com/bollard', 'followers_url': 'https://api.github.com/users/bollard/followers', 'following_url': 'https://api.github.com/users/bollard/following{/other_user}', 'gists_url': 'https://api.github.com/users/bollard/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bollard/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bollard/subscriptions', 'organizations_url': 'https://api.github.com/users/bollard/orgs', 'repos_url': 'https://api.github.com/users/bollard/repos', 'events_url': 'https://api.github.com/users/bollard/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bollard/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-04T11:42:55Z,2022-08-04T11:42:55Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd


# note, does not include today
day_offset = [-2, -1, 1, 2]
timestamps = [pd.Timestamp.now() + pd.Timedelta(days=d) for d in day_offset]

df_ts = pd.DataFrame(
    data={""offset"": day_offset},
    index=pd.Index(timestamps, name=""timestamp"")
)

print(""\n==============="")
print(""{}\n"".format(df_ts))

# want to group by the day
grouper = pd.Grouper(level=""timestamp"", freq=""D"")
grouped = df_ts.groupby(grouper)
print(""[Grouper] Groups: {}, Indicies: {}\n"".format(len(grouped.groups), len(grouped.indices)))

for key, df_group in grouped:
    print(""{}: {}"".format(key, len(df_group)))
    
    if key.date() == pd.Timestamp.now().date():
        print(""...?"") # unexpected!

df_date = pd.DataFrame(
    data={""offset"": day_offset},
    index=pd.Index(df_ts.index.date, name='date')
)

print(""\n==============="")
print(""{}\n"".format(df_date))

grouped = df_date.groupby('date')
print(""[Groupby] Groups: {}, Indicies: {}\n"".format(len(grouped.groups), len(grouped.indices)))

for key, df_group in grouped:
    print(""{}: {}"".format(key, len(df_group)))
```


### Issue Description

Hello,

In the example above, I am trying to group datetimes to dates, using the `pd.Grouper(..., freq=""D"")`, however this creates a key for a date which doesn't exist in the data. This behaviour is different to using `groupby` on dates directly (which does not create a missing key). Also note this creates a mismatch in the size of the `.groups` and the `.indices` (as the latter does _not_ include the empty reference)

This creates unexpected behaviour when you try to loop over the groups later (and have more groups than you'd expect).

This is also not particularly easy to handle on the user end (if we do not wish to reconstruct the groupby object). Instead I have resorted to looping over the `grouped.indices.keys()` and the using `get_group` to avoid the empty group.

### Expected Behavior

The empty group would not be created with the `pd.Grouper`

### Installed Versions

<details>

commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.4.3
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 22.1.2
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47963/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47963/timeline,,,,
13,https://api.github.com/repos/pandas-dev/pandas/issues/47962,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47962/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47962/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47962/events,https://github.com/pandas-dev/pandas/pull/47962,1328492289,PR_kwDOAA0YD848pJF5,47962,BUG: read_csv with engine pyarrow doesn't handle missing values,"{'login': 'MarcoGorelli', 'id': 33491632, 'node_id': 'MDQ6VXNlcjMzNDkxNjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MarcoGorelli', 'html_url': 'https://github.com/MarcoGorelli', 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers', 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}', 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions', 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs', 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos', 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,5,2022-08-04T11:39:47Z,2022-08-05T07:22:22Z,,MEMBER,,"- [x] closes #47950 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47962/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47962/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47962', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47962', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47962.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47962.patch', 'merged_at': None}"
14,https://api.github.com/repos/pandas-dev/pandas/issues/47961,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47961/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47961/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47961/events,https://github.com/pandas-dev/pandas/issues/47961,1328449752,I_kwDOAA0YD85PLojY,47961,BUG: read_csv with engine pyarrow doesn't handle parsing multiple date columns,"{'login': 'MarcoGorelli', 'id': 33491632, 'node_id': 'MDQ6VXNlcjMzNDkxNjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MarcoGorelli', 'html_url': 'https://github.com/MarcoGorelli', 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers', 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}', 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions', 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs', 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos', 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': ''}]",open,False,,[],,1,2022-08-04T11:00:14Z,2022-08-04T11:11:00Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import io

data = """"""idx,date,time
2,2000-01-01, 00:00:00
3,2000-01-01, 00:01:00
4,2000-01-01, 00:02:00
""""""

df = pd.read_csv(io.StringIO(data), parse_dates={'date2': ['date', 'time']})
print(df)
df = pd.read_csv(io.StringIO(data), parse_dates={'date2': ['date', 'time']}, engine='pyarrow')
```


### Issue Description

Without `, engine='pyarrow'`, it works fine. With it, we get

```
Traceback (most recent call last):
  File ""/home/megorelli/pandas-dev/t.py"", line 10, in <module>
    df = pd.read_csv(io.StringIO(data), parse_dates={'date2': ['date', 'time']}, engine='pyarrow')
  File ""/home/megorelli/pandas-dev/pandas/util/_decorators.py"", line 317, in wrapper
    return func(*args, **kwargs)
  File ""/home/megorelli/pandas-dev/pandas/io/parsers/readers.py"", line 943, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""/home/megorelli/pandas-dev/pandas/io/parsers/readers.py"", line 605, in _read
    return parser.read(nrows)
  File ""/home/megorelli/pandas-dev/pandas/io/parsers/readers.py"", line 1748, in read
    df = self._engine.read()  # type: ignore[attr-defined]
  File ""/home/megorelli/pandas-dev/pandas/io/parsers/arrow_parser_wrapper.py"", line 152, in read
    return self._finalize_output(frame)
  File ""/home/megorelli/pandas-dev/pandas/io/parsers/arrow_parser_wrapper.py"", line 108, in _finalize_output
    frame.columns, frame = self._do_date_conversions(frame.columns, frame)
  File ""/home/megorelli/pandas-dev/pandas/core/generic.py"", line 5852, in __setattr__
    return object.__setattr__(self, name, value)
  File ""pandas/_libs/properties.pyx"", line 69, in pandas._libs.properties.AxisProperty.__set__
    obj._set_axis(self.axis, value)
  File ""/home/megorelli/pandas-dev/pandas/core/generic.py"", line 771, in _set_axis
    self._mgr.set_axis(axis, labels)
  File ""/home/megorelli/pandas-dev/pandas/core/internals/managers.py"", line 218, in set_axis
    self._validate_set_axis(axis, new_labels)
  File ""/home/megorelli/pandas-dev/pandas/core/internals/base.py"", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

### Expected Behavior

```
                date2  idx
0 2000-01-01 00:00:00    2
1 2000-01-01 00:01:00    3
2 2000-01-01 00:02:00    4
```

### Installed Versions

<details>

/home/megorelli/pandas-dev/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn(""Setuptools is replacing distutils."")

INSTALLED VERSIONS
------------------
commit           : 690a77fe19f9229ff02987abbd487a63c2cbe1b8
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.114-16025-ge75506b9d98e
Version          : #1 SMP PREEMPT Sat Jul 16 18:52:19 PDT 2022
machine          : aarch64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+1231.g690a77fe19.dirty
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.1.0
pip              : 22.0.4
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.47.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47961/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47961/timeline,,,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/47960,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47960/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47960/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47960/events,https://github.com/pandas-dev/pandas/issues/47960,1328201471,I_kwDOAA0YD85PKr7_,47960,WEB: Review donation options for pandas,"{'login': 'datapythonista', 'id': 10058240, 'node_id': 'MDQ6VXNlcjEwMDU4MjQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/10058240?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/datapythonista', 'html_url': 'https://github.com/datapythonista', 'followers_url': 'https://api.github.com/users/datapythonista/followers', 'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}', 'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions', 'organizations_url': 'https://api.github.com/users/datapythonista/orgs', 'repos_url': 'https://api.github.com/users/datapythonista/repos', 'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}', 'received_events_url': 'https://api.github.com/users/datapythonista/received_events', 'type': 'User', 'site_admin': False}","[{'id': 32933285, 'node_id': 'MDU6TGFiZWwzMjkzMzI4NQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Admin', 'name': 'Admin', 'color': 'DDDDDD', 'default': False, 'description': 'Administrative tasks related to the pandas project'}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}, {'id': 1508144531, 'node_id': 'MDU6TGFiZWwxNTA4MTQ0NTMx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Web', 'name': 'Web', 'color': '23ef97', 'default': False, 'description': 'pandas website'}]",open,False,,[],,1,2022-08-04T07:37:52Z,2022-08-04T13:30:07Z,,MEMBER,,"In #47931 @logankilpatrick suggested that we add support for GitHub sponsors to pandas. I don't know much about it, but seems like we've got it enabled, but just providing links to our donations page and tidelift. I guess we can set it up to receive donations directly.

Besides it, we've got now https://opencollective.com/pandas which also handles donations, and I think it's intended to replace the current salsa donations we're currently using in our website.

Also, maybe we want to discuss whether out [Contribute](https://pandas.pydata.org/contribute.html) page has the visibility and the options that we want. I think naming the section `Contribute` may sound to much as helping pandas with coding. Renaming it to `Donate` may sound as just giving individual donations. Would it make sense to rename it to something else where it's more clear for visitors of the website that they can contribute code, corporate sponsorship, money... Not sure if something like `Help pandas`, `Get involved`... Probably native English speakers can find something better. Also, would it be worth adding Tidelift to the options in that page? Or anything else?","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47960/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47960/timeline,,,,
16,https://api.github.com/repos/pandas-dev/pandas/issues/47959,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47959/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47959/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47959/events,https://github.com/pandas-dev/pandas/issues/47959,1328191613,I_kwDOAA0YD85PKph9,47959,Specify the behaviour for empty input,"{'login': 'Th3nn3ss', 'id': 25160953, 'node_id': 'MDQ6VXNlcjI1MTYwOTUz', 'avatar_url': 'https://avatars.githubusercontent.com/u/25160953?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Th3nn3ss', 'html_url': 'https://github.com/Th3nn3ss', 'followers_url': 'https://api.github.com/users/Th3nn3ss/followers', 'following_url': 'https://api.github.com/users/Th3nn3ss/following{/other_user}', 'gists_url': 'https://api.github.com/users/Th3nn3ss/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Th3nn3ss/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Th3nn3ss/subscriptions', 'organizations_url': 'https://api.github.com/users/Th3nn3ss/orgs', 'repos_url': 'https://api.github.com/users/Th3nn3ss/repos', 'events_url': 'https://api.github.com/users/Th3nn3ss/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Th3nn3ss/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-08-04T07:28:48Z,2022-08-04T15:48:55Z,,CONTRIBUTOR,,"There isn't an issue for empty inputs. 

There is a need to specify the behaviour for empty input. Note that “empty” input can mean many things, and even combinations of them:

- zero rows but non-zero columns
- zero columns but non-zero rows
- zero rows and zero columns
- other: e.g., empty list provided to `agg()`

As suggested by @shwina in the Pandas Standardisation docs, the idea is to start by writing a bunch of tests across many different Pandas operations and see how many pass across libraries.

Classic example (quiz: what should this do?)

>>> df = pd.DataFrame({""a"": [], ""b"": []})
>>> df.groupby(“a”).agg({})

A starting list of operations where tests are needed would be particularly helpful, I plan to start going through them and adding all the tests.

- [ ] The above example returns a `ValueError: No objects to concatenate`, is this the expected behaviour? 
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47959/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47959/timeline,,,,
17,https://api.github.com/repos/pandas-dev/pandas/issues/47958,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47958/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47958/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47958/events,https://github.com/pandas-dev/pandas/pull/47958,1328169240,PR_kwDOAA0YD848oD6r,47958,ENH: Add `dtype` param for `pandas.Series.str.get_dummies`,"{'login': 'JeffersonQin', 'id': 30655701, 'node_id': 'MDQ6VXNlcjMwNjU1NzAx', 'avatar_url': 'https://avatars.githubusercontent.com/u/30655701?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JeffersonQin', 'html_url': 'https://github.com/JeffersonQin', 'followers_url': 'https://api.github.com/users/JeffersonQin/followers', 'following_url': 'https://api.github.com/users/JeffersonQin/following{/other_user}', 'gists_url': 'https://api.github.com/users/JeffersonQin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JeffersonQin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JeffersonQin/subscriptions', 'organizations_url': 'https://api.github.com/users/JeffersonQin/orgs', 'repos_url': 'https://api.github.com/users/JeffersonQin/repos', 'events_url': 'https://api.github.com/users/JeffersonQin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JeffersonQin/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-08-04T07:06:59Z,2022-08-04T10:22:49Z,,NONE,,"- [ ] closes #47872 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47958/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47958/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47958', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47958', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47958.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47958.patch', 'merged_at': None}"
18,https://api.github.com/repos/pandas-dev/pandas/issues/47956,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47956/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47956/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47956/events,https://github.com/pandas-dev/pandas/pull/47956,1328002838,PR_kwDOAA0YD848ng3Q,47956,Issue46882,"{'login': 'Mehgarg', 'id': 65103188, 'node_id': 'MDQ6VXNlcjY1MTAzMTg4', 'avatar_url': 'https://avatars.githubusercontent.com/u/65103188?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Mehgarg', 'html_url': 'https://github.com/Mehgarg', 'followers_url': 'https://api.github.com/users/Mehgarg/followers', 'following_url': 'https://api.github.com/users/Mehgarg/following{/other_user}', 'gists_url': 'https://api.github.com/users/Mehgarg/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Mehgarg/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Mehgarg/subscriptions', 'organizations_url': 'https://api.github.com/users/Mehgarg/orgs', 'repos_url': 'https://api.github.com/users/Mehgarg/repos', 'events_url': 'https://api.github.com/users/Mehgarg/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Mehgarg/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,4,2022-08-04T03:03:40Z,2022-08-05T11:21:59Z,,CONTRIBUTOR,,"- [ ] closes #46882 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47956/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47956/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47956', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47956', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47956.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47956.patch', 'merged_at': None}"
19,https://api.github.com/repos/pandas-dev/pandas/issues/47955,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47955/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47955/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47955/events,https://github.com/pandas-dev/pandas/issues/47955,1327997065,I_kwDOAA0YD85PJ6CJ,47955,"PERF: .clip with datetime64[ns, UTC] Series regressed","{'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}","[{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries', 'name': 'Timeseries', 'color': 'AFEEEE', 'default': False, 'description': None}, {'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}]",open,False,,[],,0,2022-08-04T02:52:57Z,2022-08-04T03:11:04Z,,CONTRIBUTOR,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.


### Reproducible Example

1.2.5
```
i = pd.date_range('20220101', periods=100000, freq='s', tz='UTC')
clipper = i[0:1000].repeat(100)
%timeit pd.Series(i).clip(upper=clipper)
3.47 ms ± 53 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

1.3.5
```
i = pd.date_range('20220101', periods=100000, freq='s', tz='UTC')
clipper = i[0:1000].repeat(100)
%timeit pd.Series(i).clip(upper=clipper)
452 ms ± 3.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

1.4.3
```
i = pd.date_range('20220101', periods=100000, freq='s', tz='UTC')
clipper = i[0:1000].repeat(100)
%timeit pd.Series(i).clip(upper=clipper)
132 ms ± 794 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

This work-around gets close to the original (you can do better by using `np.where` as we do in the impl of clip, but nbd).
```
i = pd.date_range('20220101', periods=100000, freq='s', tz='UTC')
clipper = i[0:1000].repeat(100)
%timeit pd.Series(pd.to_datetime(pd.Series(i.view('i8')).clip(upper=clipper.view('i8')), utc=True))
6.08 ms ± 62.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```


### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>


### Prior Performance

_No response_","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47955/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47955/timeline,,,,
20,https://api.github.com/repos/pandas-dev/pandas/issues/47953,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47953/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47953/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47953/events,https://github.com/pandas-dev/pandas/issues/47953,1327873407,I_kwDOAA0YD85PJb1_,47953,BUG: inconsistent behavior of DateOffset,"{'login': 'colomb8', 'id': 71855882, 'node_id': 'MDQ6VXNlcjcxODU1ODgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/71855882?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/colomb8', 'html_url': 'https://github.com/colomb8', 'followers_url': 'https://api.github.com/users/colomb8/followers', 'following_url': 'https://api.github.com/users/colomb8/following{/other_user}', 'gists_url': 'https://api.github.com/users/colomb8/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/colomb8/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/colomb8/subscriptions', 'organizations_url': 'https://api.github.com/users/colomb8/orgs', 'repos_url': 'https://api.github.com/users/colomb8/repos', 'events_url': 'https://api.github.com/users/colomb8/events{/privacy}', 'received_events_url': 'https://api.github.com/users/colomb8/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-03T23:06:10Z,2022-08-03T23:06:10Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
   'S':[pd.Timestamp('2019-04-30')],
   'A':[pd.DateOffset(months=1)]
   })

# FIRST TEST
>>> df['S'] + 26 * df['A']
0   2021-06-30
dtype: datetime64[ns]

# SECOND TEST
>>> df['S'].iloc[0] + 26 * df['A'].iloc[0]
Timestamp('2021-06-28 00:00:00')
```


### Issue Description

It seems like multiplying a DateOffset by constant leads to an inconsistent behavior: the first test gives 30/6 while the second 28/6 

### Expected Behavior

In any case it should be 2021-06-30

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.10.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Italian_Italy.1252

pandas           : 1.3.5
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.1.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47953/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47953/timeline,,,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/47952,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47952/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47952/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47952/events,https://github.com/pandas-dev/pandas/pull/47952,1327818649,PR_kwDOAA0YD848m68b,47952,DEBUG: Debug failing macpython wheels,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-08-03T21:39:41Z,2022-08-03T22:02:33Z,,MEMBER,,"might be because of a change in hypothesis
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47952/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47952/timeline,,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47952', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47952', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47952.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47952.patch', 'merged_at': None}"
22,https://api.github.com/repos/pandas-dev/pandas/issues/47950,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47950/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47950/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47950/events,https://github.com/pandas-dev/pandas/issues/47950,1327774630,I_kwDOAA0YD85PJDum,47950,BUG: read_csv with engine pyarrow doesn't handle missing values,"{'login': 'MarcoGorelli', 'id': 33491632, 'node_id': 'MDQ6VXNlcjMzNDkxNjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MarcoGorelli', 'html_url': 'https://github.com/MarcoGorelli', 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers', 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}', 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions', 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs', 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos', 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': ''}]",open,False,,[],,2,2022-08-03T20:50:08Z,2022-08-04T10:51:02Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import io

data = """"""idx,date
2,2000-01-01
,
""""""

print('pyarrow engine', pd.read_csv(io.StringIO(data), parse_dates=['date'], engine='pyarrow'))
print('default engine', pd.read_csv(io.StringIO(data), parse_dates=['date']))
```


### Issue Description


Like this, we get:

```
pyarrow engine    idx        date
0  2.0  2000-01-01
1  NaN        None
default engine    idx       date
0  2.0 2000-01-01
1  NaN        NaT
```

### Expected Behavior

I'd expect:
```
pyarrow engine    idx        date
0  2.0  2000-01-01
1  NaN        NaT
default engine    idx       date
0  2.0 2000-01-01
1  NaN        NaT
```

### Installed Versions

<details>

/home/megorelli/pandas-dev/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn(""Setuptools is replacing distutils."")

INSTALLED VERSIONS
------------------
commit           : 61464f8cad07271114af7668bbae158ba963126c
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.114-16025-ge75506b9d98e
Version          : #1 SMP PREEMPT Sat Jul 16 18:52:19 PDT 2022
machine          : aarch64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+1230.g61464f8cad.dirty
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.1.0
pip              : 22.0.4
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.47.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47950/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47950/timeline,,,,
23,https://api.github.com/repos/pandas-dev/pandas/issues/47948,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47948/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47948/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47948/events,https://github.com/pandas-dev/pandas/pull/47948,1327654597,PR_kwDOAA0YD848mYuF,47948,DOC: Plotting / Visualization without Jupyter,"{'login': 'tpackard1', 'id': 46908522, 'node_id': 'MDQ6VXNlcjQ2OTA4NTIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/46908522?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tpackard1', 'html_url': 'https://github.com/tpackard1', 'followers_url': 'https://api.github.com/users/tpackard1/followers', 'following_url': 'https://api.github.com/users/tpackard1/following{/other_user}', 'gists_url': 'https://api.github.com/users/tpackard1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tpackard1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tpackard1/subscriptions', 'organizations_url': 'https://api.github.com/users/tpackard1/orgs', 'repos_url': 'https://api.github.com/users/tpackard1/repos', 'events_url': 'https://api.github.com/users/tpackard1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tpackard1/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 74, 'closed_issues': 1240, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-08-05T12:56:48Z', 'due_on': '2022-07-31T07:00:00Z', 'closed_at': None}",3,2022-08-03T18:56:06Z,2022-08-05T06:38:00Z,,NONE,,"Added a note at the top of the page clarifying that the examples assume you're working jupyter.  @MarcoGorelli asked to be tagged to this PR. Hopefully I did everything correctly as this is my first PR.

- [x] closes #47861 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47948/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47948/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47948', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47948', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47948.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47948.patch', 'merged_at': None}"
24,https://api.github.com/repos/pandas-dev/pandas/issues/47947,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47947/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47947/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47947/events,https://github.com/pandas-dev/pandas/pull/47947,1327607707,PR_kwDOAA0YD848mO3I,47947,BUG: Propagating precision to interval dtype #43913,"{'login': 'SomtochiUmeh', 'id': 74836691, 'node_id': 'MDQ6VXNlcjc0ODM2Njkx', 'avatar_url': 'https://avatars.githubusercontent.com/u/74836691?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/SomtochiUmeh', 'html_url': 'https://github.com/SomtochiUmeh', 'followers_url': 'https://api.github.com/users/SomtochiUmeh/followers', 'following_url': 'https://api.github.com/users/SomtochiUmeh/following{/other_user}', 'gists_url': 'https://api.github.com/users/SomtochiUmeh/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/SomtochiUmeh/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/SomtochiUmeh/subscriptions', 'organizations_url': 'https://api.github.com/users/SomtochiUmeh/orgs', 'repos_url': 'https://api.github.com/users/SomtochiUmeh/repos', 'events_url': 'https://api.github.com/users/SomtochiUmeh/events{/privacy}', 'received_events_url': 'https://api.github.com/users/SomtochiUmeh/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-08-03T18:06:33Z,2022-08-04T20:26:36Z,,CONTRIBUTOR,,"- [x] closes #43913
- [x] [test_frame_equal_tolerance() test added and passed]
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47947/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47947/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47947', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47947', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47947.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47947.patch', 'merged_at': None}"
25,https://api.github.com/repos/pandas-dev/pandas/issues/47946,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47946/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47946/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47946/events,https://github.com/pandas-dev/pandas/pull/47946,1327602949,PR_kwDOAA0YD848mN6_,47946,Fix bug in pd.merge when joining two Series,"{'login': 'nsarang', 'id': 25885841, 'node_id': 'MDQ6VXNlcjI1ODg1ODQx', 'avatar_url': 'https://avatars.githubusercontent.com/u/25885841?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/nsarang', 'html_url': 'https://github.com/nsarang', 'followers_url': 'https://api.github.com/users/nsarang/followers', 'following_url': 'https://api.github.com/users/nsarang/following{/other_user}', 'gists_url': 'https://api.github.com/users/nsarang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/nsarang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/nsarang/subscriptions', 'organizations_url': 'https://api.github.com/users/nsarang/orgs', 'repos_url': 'https://api.github.com/users/nsarang/repos', 'events_url': 'https://api.github.com/users/nsarang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/nsarang/received_events', 'type': 'User', 'site_admin': False}","[{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 1628184320, 'node_id': 'MDU6TGFiZWwxNjI4MTg0MzIw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Warnings', 'name': 'Warnings', 'color': 'f2f074', 'default': False, 'description': 'Warnings that appear or should be added to pandas'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/96', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96/labels', 'id': 8104401, 'node_id': 'MI_kwDOAA0YD84Ae6nR', 'number': 96, 'title': '1.4.4', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 35, 'closed_issues': 42, 'state': 'open', 'created_at': '2022-06-21T19:44:05Z', 'updated_at': '2022-08-05T11:51:43Z', 'due_on': '2022-08-31T07:00:00Z', 'closed_at': None}",4,2022-08-03T18:02:05Z,2022-08-03T18:19:18Z,,NONE,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

There is a small bug/typo in the warning of message of `pd.merge` when merging two `Series` of different levels which results in an exception.  

Thrown error message:
`AttributeError: 'Series' object has no attribute 'columns'`","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47946/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47946/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47946', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47946', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47946.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47946.patch', 'merged_at': None}"
26,https://api.github.com/repos/pandas-dev/pandas/issues/47944,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47944/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47944/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47944/events,https://github.com/pandas-dev/pandas/issues/47944,1327408033,I_kwDOAA0YD85PHqOh,47944,BUG: Ordering of `columns` is not preserved in `pd.read_orc`,"{'login': 'galipremsagar', 'id': 11664259, 'node_id': 'MDQ6VXNlcjExNjY0MjU5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11664259?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/galipremsagar', 'html_url': 'https://github.com/galipremsagar', 'followers_url': 'https://api.github.com/users/galipremsagar/followers', 'following_url': 'https://api.github.com/users/galipremsagar/following{/other_user}', 'gists_url': 'https://api.github.com/users/galipremsagar/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/galipremsagar/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/galipremsagar/subscriptions', 'organizations_url': 'https://api.github.com/users/galipremsagar/orgs', 'repos_url': 'https://api.github.com/users/galipremsagar/repos', 'events_url': 'https://api.github.com/users/galipremsagar/events{/privacy}', 'received_events_url': 'https://api.github.com/users/galipremsagar/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-03T15:28:28Z,2022-08-03T15:28:28Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
In [5]: import cudf

In [6]: df = cudf.DataFrame({""a"": [1, 2, 3], ""b"": [""a"", ""b"", ""c""]})

In [7]: df.to_orc(""abc"")

In [8]: df.to_parquet(""abc.parquet"")

In [9]: import pandas as pd

In [10]: pd.read_parquet(""abc.parquet"", columns=['b', 'a'])
Out[10]: 
   b  a
0  a  1
1  b  2
2  c  3

In [11]: pd.read_orc(""abc"", columns=['b', 'a'])
Out[11]: 
   a  b
0  1  a
1  2  b
2  3  c

In [12]: pd.__version__
Out[12]: '1.4.3'
```


### Issue Description

The ordering of columns in the output is being respected in `pd.read_parquet` but not in `pd.read_orc`. 

### Expected Behavior

The expected behavior is the columns in the output dataframe are in the same order of `columns`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.3.0
pip              : 22.2.1
Cython           : 0.29.32
pytest           : 7.1.2
hypothesis       : 6.47.1
sphinx           : 5.1.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2022.7.1
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : None
numba            : 0.55.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.7.1
scipy            : 1.9.0
snappy           : 
sqlalchemy       : 1.4.39
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47944/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47944/timeline,,,,
27,https://api.github.com/repos/pandas-dev/pandas/issues/47942,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47942/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47942/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47942/events,https://github.com/pandas-dev/pandas/issues/47942,1327099266,I_kwDOAA0YD85PGe2C,47942,BUG: Resampler.quantile produce inconsistent results when interpolation='nearest' and q=0.5,"{'login': 'henrykwong', 'id': 20166805, 'node_id': 'MDQ6VXNlcjIwMTY2ODA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/20166805?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/henrykwong', 'html_url': 'https://github.com/henrykwong', 'followers_url': 'https://api.github.com/users/henrykwong/followers', 'following_url': 'https://api.github.com/users/henrykwong/following{/other_user}', 'gists_url': 'https://api.github.com/users/henrykwong/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/henrykwong/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/henrykwong/subscriptions', 'organizations_url': 'https://api.github.com/users/henrykwong/orgs', 'repos_url': 'https://api.github.com/users/henrykwong/repos', 'events_url': 'https://api.github.com/users/henrykwong/events{/privacy}', 'received_events_url': 'https://api.github.com/users/henrykwong/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-08-03T11:47:33Z,2022-08-05T12:46:06Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'x': [i for i in range(100)]})
df.index = pd.to_datetime(df['x'], unit='s')

res1 = df.resample('{}S'.format(n)).apply(lambda x: x.quantile(0.5, interpolation='nearest')).iloc[0][0]
res2 = df.resample('{}S'.format(n)).quantile(0.5, interpolation='nearest').iloc[0][0]
print(""result from Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest'): \t{}"".format(res1))
print(""result from Resample.quantile(q=0.5, interpolation='nearest'): \t{}"".format(res2))
```


### Issue Description

`Resample.quantile(q=0.5, interpolation='nearest)` and `Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest)` produce different results. Behaviours were consistent when using other interpolation method, i.e. {‘linear’, ‘lower’, ‘higher’, ‘midpoint’} OR when `q!=0.5`

### Expected Behavior

Actual result:
result from `Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest')`: 	50
result from `Resample.quantile(q=0.5, interpolation='nearest')`: 	49

Expected result:
result from `Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest')`: 	50
result from `Resample.quantile(q=0.5, interpolation='nearest')`: 	50


### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-41-generic
Version          : #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.3
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 52.0.0.post20210125
pip              : 21.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.4.3
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: 0.10.0
bs4              : 4.10.0
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.4.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47942/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47942/timeline,,,,
28,https://api.github.com/repos/pandas-dev/pandas/issues/47941,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47941/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47941/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47941/events,https://github.com/pandas-dev/pandas/issues/47941,1326954849,I_kwDOAA0YD85PF7lh,47941,BUG: union of lists of DatetimeIndex generates ValueErrors,"{'login': 'btodac', 'id': 45459748, 'node_id': 'MDQ6VXNlcjQ1NDU5NzQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/45459748?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/btodac', 'html_url': 'https://github.com/btodac', 'followers_url': 'https://api.github.com/users/btodac/followers', 'following_url': 'https://api.github.com/users/btodac/following{/other_user}', 'gists_url': 'https://api.github.com/users/btodac/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/btodac/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/btodac/subscriptions', 'organizations_url': 'https://api.github.com/users/btodac/orgs', 'repos_url': 'https://api.github.com/users/btodac/repos', 'events_url': 'https://api.github.com/users/btodac/events{/privacy}', 'received_events_url': 'https://api.github.com/users/btodac/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-08-03T09:44:48Z,2022-08-03T09:44:48Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
a = pd.date_range(start=pd.Timestamp.today() - pd.Timedelta(days=30), end=pd.Timestamp.today())
b = [a[:5], a[5:10], a[5:7], a[10:]]
b[0].union(b[1:])
# and
#b[0].union(b[1:2])
```


### Issue Description

The first example fails with ValueError: Lengths must match to compare, when performing a monotonic data check. (pandas/core/indexes/base.py"", line 6672, in _cmp_method raise ValueError(""Lengths must match to compare"")
The second example fails with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all(), when performing a monotonic data check (File ""pandas/_libs/algos.pyx"", line 754, in pandas._libs.algos.is_monotonic).

`union_many()` works fine but generates a soon to be deprecated warning

### Expected Behavior

import pandas as pd
a = pd.date_range(start=pd.Timestamp.today() - pd.Timedelta(days=30), end=pd.Timestamp.today())
b = [a[:5], a[5:10], a[5:7], a[10:]]
b[0].union_many(b[1:])

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.10.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-122-generic
Version          : #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 60.10.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.0
IPython          : 7.32.0
pandas_datareader: 0.10.0
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47941/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47941/timeline,,,,
29,https://api.github.com/repos/pandas-dev/pandas/issues/47937,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47937/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47937/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47937/events,https://github.com/pandas-dev/pandas/pull/47937,1326736134,PR_kwDOAA0YD848jTMa,47937,WARN : extended stack level check to include all classes of warnings ,"{'login': 'shourya5', 'id': 73142986, 'node_id': 'MDQ6VXNlcjczMTQyOTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/73142986?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/shourya5', 'html_url': 'https://github.com/shourya5', 'followers_url': 'https://api.github.com/users/shourya5/followers', 'following_url': 'https://api.github.com/users/shourya5/following{/other_user}', 'gists_url': 'https://api.github.com/users/shourya5/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/shourya5/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/shourya5/subscriptions', 'organizations_url': 'https://api.github.com/users/shourya5/orgs', 'repos_url': 'https://api.github.com/users/shourya5/repos', 'events_url': 'https://api.github.com/users/shourya5/events{/privacy}', 'received_events_url': 'https://api.github.com/users/shourya5/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-08-03T06:22:13Z,2022-08-03T20:30:51Z,,CONTRIBUTOR,,"- [x] closes #47919 
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47937/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47937/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47937', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47937', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47937.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47937.patch', 'merged_at': None}"
